openapi: 3.2.0
info:
  version: 1.0.0
  title: Listmonk Admin API
  description: The API collection for listmonk
  license:
    name: AGPL-3.0 license
    url: https://github.com/knadh/listmonk/blob/master/LICENSE
servers:
- description: Listmonk Developement Server
  url: http://localhost:9000/api
tags:
- name: Admin
  description: Admin API
paths:
  /admin/reload:
    post:
      tags:
      - Admin
      description: restarts the app
      operationId: reloadApp
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
      summary: Reload app
      x-summary-source: derived
